# This workflow will install Python dependencies, run ruff for formatting and fixing
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
        
name: Ruff

on:
  push: {}
  pull_request: {}

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Format code with Ruff
      id: format
      run: |
        ruff format
#        echo "FORMATTED=true" >> $GITHUB_ENV
      
    - name: Check code with Ruff and fix issues
      id: check
      run: |
        ruff check --fix
#        echo "FIXED=true" >> $GITHUB_ENV

    - uses: chartboost/ruff-action@v1

#    - name: Commit changes if formatted/fixed
#      if: env.FORMATTED == 'true' || env.FIXED == 'true'
#      run: |
#        git config --local user.email "e11912008@student.tuwien.ac.at"
#        git config --local user.name "Simon Jordan"
#        git add .
#        git commit -m "Ruff formatted/fixed file(s)"
#        git push

#    - name: Commit changes if formatted and fixed
#      if: env.FORMATTED == 'true' && env.FIXED == 'true'
#      run: |
#        git config --local user.email "e11912008@student.tuwien.ac.at"
#        git config --local user.name "Simon Jordan"
#        git add .
#        git commit -m "Ruff formatted and fixed file(s)"
#        git push
    
#    - name: Commit changes if only formatted
#      if: env.FORMATTED == 'true' && env.FIXED != 'true'
#      run: |
#        git config --local user.email "e11912008@student.tuwien.ac.at"
#        git config --local user.name "Simon Jordan"
#        git add .
#        git commit -m "Ruff formatted file(s)"
#        git push
    
#    - name: Commit changes if only fixed
#      if: env.FIXED == 'true' && env.FORMATTED != 'true'
#      run: |
#        git config --local user.email "e11912008@student.tuwien.ac.at"
#        git config --local user.name "Simon Jordan"
#        git add .
#        git commit -m "Ruff fixed file(s)"
#        git push
