# This workflow will install Python dependencies, run ruff for checking at pull_request
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
        
name: Ruff_pull_request

on:
  pull_request: {}

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        
    - uses: chartboost/ruff-action@v1
