      
        
        
name: Ruff

on:
  push: {}
  pull_request: {}

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Format code with Ruff
      run: ruff format
      
    - name: Check code with Ruff and fix issues
      run: ruff check --fix
      
    - uses: chartboost/ruff-action@v1