# This workflow will install Python dependencies, run ruff for formatting and fixing
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
        
name: Ruff

on:
  push: {}
  pull_request: {}

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - uses: chartboost/ruff-action@v1
    
    - name: Format code with Ruff
      run: |
        ruff format
        echo "::set-output name=formatted::$(git status --porcelain)"
      
    - name: Check code with Ruff and fix issues
      run: |
        ruff check --fix
        echo "::set-output name=fixed::$(git status --porcelain)"

    - name: Commit changes
      if: steps.ruff.outputs.formatted != '' || steps.ruff.outputs.fixed != ''
      run: |
        git config --local user.email "e11912008@student.tuwien.ac.at"
        git config --local user.name "Simon Jordan"
        git add .
        git commit -m "Ruff formatted/fixed files"
        git push