name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: npm install -g ruff-cli
      - name: Format code with Ruff
        run: ruff format
      - name: Check code with Ruff and fix issues
        run: ruff check --fix